// AUTO-GENERATED by ffigen - DO NOT EDIT
// Run `dart run ffigen` to regenerate
//
// ignore_for_file: non_constant_identifier_names
// ignore_for_file: unused_field
// ignore_for_file: unused_element
// ignore_for_file: camel_case_types

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint
@ffi.DefaultAsset('package:espeak/espeak_native')
library;

import 'dart:ffi' as ffi;

@ffi.Native<
    ffi.Int Function(ffi.UnsignedInt, ffi.Int, ffi.Pointer<ffi.Char>,
        ffi.Int)>(symbol: 'espeak_Initialize')
external int _espeak_Initialize(
  int output,
  int buflength,
  ffi.Pointer<ffi.Char> path,
  int options,
);

int espeak_Initialize(
  espeak_AUDIO_OUTPUT output,
  int buflength,
  ffi.Pointer<ffi.Char> path,
  int options,
) =>
    _espeak_Initialize(
      output.value,
      buflength,
      path,
      options,
    );

@ffi.Native<
    ffi.Pointer<ffi.Char> Function(
        ffi.Pointer<ffi.Pointer<ffi.Void>>, ffi.Int, ffi.Int)>()
external ffi.Pointer<ffi.Char> espeak_TextToPhonemes(
  ffi.Pointer<ffi.Pointer<ffi.Void>> textptr,
  int textmode,
  int phonememode,
);

@ffi.Native<
    ffi.Pointer<ffi.Char> Function(ffi.Pointer<ffi.Pointer<ffi.Void>>, ffi.Int,
        ffi.Int, ffi.Pointer<ffi.Int>)>()
external ffi.Pointer<ffi.Char> espeak_TextToPhonemesWithTerminator(
  ffi.Pointer<ffi.Pointer<ffi.Void>> textptr,
  int textmode,
  int phonememode,
  ffi.Pointer<ffi.Int> terminator,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<ffi.Char>)>(
    symbol: 'espeak_SetVoiceByName')
external int _espeak_SetVoiceByName(
  ffi.Pointer<ffi.Char> name,
);

espeak_ERROR espeak_SetVoiceByName(
  ffi.Pointer<ffi.Char> name,
) =>
    espeak_ERROR.fromValue(_espeak_SetVoiceByName(
      name,
    ));

@ffi.Native<ffi.Int Function()>(symbol: 'espeak_Terminate')
external int _espeak_Terminate();

espeak_ERROR espeak_Terminate() => espeak_ERROR.fromValue(_espeak_Terminate());

@ffi.Native<ffi.Void Function(ffi.Pointer<ffi.Char>)>()
external void espeak_ng_InitializePath(
  ffi.Pointer<ffi.Char> path,
);

@ffi.Native<ffi.UnsignedInt Function(ffi.Pointer<espeak_ng_ERROR_CONTEXT>)>(
    symbol: 'espeak_ng_Initialize')
external int _espeak_ng_Initialize(
  ffi.Pointer<espeak_ng_ERROR_CONTEXT> context,
);

espeak_ng_STATUS espeak_ng_Initialize(
  ffi.Pointer<espeak_ng_ERROR_CONTEXT> context,
) =>
    espeak_ng_STATUS.fromValue(_espeak_ng_Initialize(
      context,
    ));

@ffi.Native<ffi.UnsignedInt Function()>(symbol: 'espeak_ng_Terminate')
external int _espeak_ng_Terminate();

espeak_ng_STATUS espeak_ng_Terminate() =>
    espeak_ng_STATUS.fromValue(_espeak_ng_Terminate());

@ffi.Native<
        ffi.UnsignedInt Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<__sFILE>,
            ffi.Int,
            ffi.Pointer<espeak_ng_ERROR_CONTEXT>)>(
    symbol: 'espeak_ng_CompileDictionary')
external int _espeak_ng_CompileDictionary(
  ffi.Pointer<ffi.Char> dsource,
  ffi.Pointer<ffi.Char> dict_name,
  ffi.Pointer<__sFILE> log,
  int flags,
  ffi.Pointer<espeak_ng_ERROR_CONTEXT> context,
);

espeak_ng_STATUS espeak_ng_CompileDictionary(
  ffi.Pointer<ffi.Char> dsource,
  ffi.Pointer<ffi.Char> dict_name,
  ffi.Pointer<__sFILE> log,
  int flags,
  ffi.Pointer<espeak_ng_ERROR_CONTEXT> context,
) =>
    espeak_ng_STATUS.fromValue(_espeak_ng_CompileDictionary(
      dsource,
      dict_name,
      log,
      flags,
      context,
    ));

@ffi.Native<
        ffi.UnsignedInt Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>,
            ffi.Pointer<__sFILE>, ffi.Pointer<espeak_ng_ERROR_CONTEXT>)>(
    symbol: 'espeak_ng_CompileIntonationPath')
external int _espeak_ng_CompileIntonationPath(
  ffi.Pointer<ffi.Char> source_path,
  ffi.Pointer<ffi.Char> destination_path,
  ffi.Pointer<__sFILE> log,
  ffi.Pointer<espeak_ng_ERROR_CONTEXT> context,
);

espeak_ng_STATUS espeak_ng_CompileIntonationPath(
  ffi.Pointer<ffi.Char> source_path,
  ffi.Pointer<ffi.Char> destination_path,
  ffi.Pointer<__sFILE> log,
  ffi.Pointer<espeak_ng_ERROR_CONTEXT> context,
) =>
    espeak_ng_STATUS.fromValue(_espeak_ng_CompileIntonationPath(
      source_path,
      destination_path,
      log,
      context,
    ));

@ffi.Native<
        ffi.UnsignedInt Function(
            ffi.Long,
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<__sFILE>,
            ffi.Pointer<espeak_ng_ERROR_CONTEXT>)>(
    symbol: 'espeak_ng_CompilePhonemeDataPath')
external int _espeak_ng_CompilePhonemeDataPath(
  int rate,
  ffi.Pointer<ffi.Char> source_path,
  ffi.Pointer<ffi.Char> destination_path,
  ffi.Pointer<__sFILE> log,
  ffi.Pointer<espeak_ng_ERROR_CONTEXT> context,
);

espeak_ng_STATUS espeak_ng_CompilePhonemeDataPath(
  int rate,
  ffi.Pointer<ffi.Char> source_path,
  ffi.Pointer<ffi.Char> destination_path,
  ffi.Pointer<__sFILE> log,
  ffi.Pointer<espeak_ng_ERROR_CONTEXT> context,
) =>
    espeak_ng_STATUS.fromValue(_espeak_ng_CompilePhonemeDataPath(
      rate,
      source_path,
      destination_path,
      log,
      context,
    ));

final class __sbuf extends ffi.Struct {
  external ffi.Pointer<ffi.UnsignedChar> _base;

  @ffi.Int()
  external int _size;
}

final class __sFILEX extends ffi.Opaque {}

final class __sFILE extends ffi.Struct {
  external ffi.Pointer<ffi.UnsignedChar> _p;

  @ffi.Int()
  external int _r;

  @ffi.Int()
  external int _w;

  @ffi.Short()
  external int _flags;

  @ffi.Short()
  external int _file;

  external __sbuf _bf;

  @ffi.Int()
  external int _lbfsize;

  external ffi.Pointer<ffi.Void> _cookie;

  external ffi
      .Pointer<ffi.NativeFunction<ffi.Int Function(ffi.Pointer<ffi.Void>)>>
      _close;

  external ffi.Pointer<
      ffi.NativeFunction<
          ffi.Int Function(
              ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Char>, ffi.Int)>> _read;

  external ffi.Pointer<
      ffi.NativeFunction<
          ffi.LongLong Function(
              ffi.Pointer<ffi.Void>, ffi.LongLong, ffi.Int)>> _seek;

  external ffi.Pointer<
      ffi.NativeFunction<
          ffi.Int Function(
              ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Char>, ffi.Int)>> _write;

  external __sbuf _ub;

  external ffi.Pointer<__sFILEX> _extra;

  @ffi.Int()
  external int _ur;

  @ffi.Array.multi([3])
  external ffi.Array<ffi.UnsignedChar> _ubuf;

  @ffi.Array.multi([1])
  external ffi.Array<ffi.UnsignedChar> _nbuf;

  external __sbuf _lb;

  @ffi.Int()
  external int _blksize;

  @ffi.LongLong()
  external int _offset;
}

enum espeak_EVENT_TYPE {
  espeakEVENT_LIST_TERMINATED(0),
  espeakEVENT_WORD(1),
  espeakEVENT_SENTENCE(2),
  espeakEVENT_MARK(3),
  espeakEVENT_PLAY(4),
  espeakEVENT_END(5),
  espeakEVENT_MSG_TERMINATED(6),
  espeakEVENT_PHONEME(7),
  espeakEVENT_SAMPLERATE(8);

  final int value;
  const espeak_EVENT_TYPE(this.value);

  static espeak_EVENT_TYPE fromValue(int value) => switch (value) {
        0 => espeakEVENT_LIST_TERMINATED,
        1 => espeakEVENT_WORD,
        2 => espeakEVENT_SENTENCE,
        3 => espeakEVENT_MARK,
        4 => espeakEVENT_PLAY,
        5 => espeakEVENT_END,
        6 => espeakEVENT_MSG_TERMINATED,
        7 => espeakEVENT_PHONEME,
        8 => espeakEVENT_SAMPLERATE,
        _ => throw ArgumentError('Unknown value for espeak_EVENT_TYPE: $value'),
      };
}

enum espeak_POSITION_TYPE {
  POS_CHARACTER(1),
  POS_WORD(2),
  POS_SENTENCE(3);

  final int value;
  const espeak_POSITION_TYPE(this.value);

  static espeak_POSITION_TYPE fromValue(int value) => switch (value) {
        1 => POS_CHARACTER,
        2 => POS_WORD,
        3 => POS_SENTENCE,
        _ =>
          throw ArgumentError('Unknown value for espeak_POSITION_TYPE: $value'),
      };
}

enum espeak_AUDIO_OUTPUT {
  AUDIO_OUTPUT_PLAYBACK(0),
  AUDIO_OUTPUT_RETRIEVAL(1),
  AUDIO_OUTPUT_SYNCHRONOUS(2),
  AUDIO_OUTPUT_SYNCH_PLAYBACK(3);

  final int value;
  const espeak_AUDIO_OUTPUT(this.value);

  static espeak_AUDIO_OUTPUT fromValue(int value) => switch (value) {
        0 => AUDIO_OUTPUT_PLAYBACK,
        1 => AUDIO_OUTPUT_RETRIEVAL,
        2 => AUDIO_OUTPUT_SYNCHRONOUS,
        3 => AUDIO_OUTPUT_SYNCH_PLAYBACK,
        _ =>
          throw ArgumentError('Unknown value for espeak_AUDIO_OUTPUT: $value'),
      };
}

enum espeak_ERROR {
  EE_OK(0),
  EE_INTERNAL_ERROR(-1),
  EE_BUFFER_FULL(1),
  EE_NOT_FOUND(2);

  final int value;
  const espeak_ERROR(this.value);

  static espeak_ERROR fromValue(int value) => switch (value) {
        0 => EE_OK,
        -1 => EE_INTERNAL_ERROR,
        1 => EE_BUFFER_FULL,
        2 => EE_NOT_FOUND,
        _ => throw ArgumentError('Unknown value for espeak_ERROR: $value'),
      };
}

/// /
enum espeak_PARAMETER {
  espeakSILENCE(0),
  espeakRATE(1),
  espeakVOLUME(2),
  espeakPITCH(3),
  espeakRANGE(4),
  espeakPUNCTUATION(5),
  espeakCAPITALS(6),
  espeakWORDGAP(7),
  espeakOPTIONS(8),
  espeakINTONATION(9),
  espeakSSML_BREAK_MUL(10),
  espeakRESERVED2(11),
  espeakEMPHASIS(12),
  espeakLINELENGTH(13),
  espeakVOICETYPE(14),
  N_SPEECH_PARAM(15);

  final int value;
  const espeak_PARAMETER(this.value);

  static espeak_PARAMETER fromValue(int value) => switch (value) {
        0 => espeakSILENCE,
        1 => espeakRATE,
        2 => espeakVOLUME,
        3 => espeakPITCH,
        4 => espeakRANGE,
        5 => espeakPUNCTUATION,
        6 => espeakCAPITALS,
        7 => espeakWORDGAP,
        8 => espeakOPTIONS,
        9 => espeakINTONATION,
        10 => espeakSSML_BREAK_MUL,
        11 => espeakRESERVED2,
        12 => espeakEMPHASIS,
        13 => espeakLINELENGTH,
        14 => espeakVOICETYPE,
        15 => N_SPEECH_PARAM,
        _ => throw ArgumentError('Unknown value for espeak_PARAMETER: $value'),
      };
}

enum espeak_PUNCT_TYPE {
  espeakPUNCT_NONE(0),
  espeakPUNCT_ALL(1),
  espeakPUNCT_SOME(2);

  final int value;
  const espeak_PUNCT_TYPE(this.value);

  static espeak_PUNCT_TYPE fromValue(int value) => switch (value) {
        0 => espeakPUNCT_NONE,
        1 => espeakPUNCT_ALL,
        2 => espeakPUNCT_SOME,
        _ => throw ArgumentError('Unknown value for espeak_PUNCT_TYPE: $value'),
      };
}

/// /
final class espeak_VOICE extends ffi.Struct {
  external ffi.Pointer<ffi.Char> name;

  external ffi.Pointer<ffi.Char> languages;

  external ffi.Pointer<ffi.Char> identifier;

  @ffi.UnsignedChar()
  external int gender;

  @ffi.UnsignedChar()
  external int age;

  @ffi.UnsignedChar()
  external int variant;

  @ffi.UnsignedChar()
  external int xx1;

  @ffi.Int()
  external int score;

  external ffi.Pointer<ffi.Void> spare;
}

enum espeak_ng_STATUS {
  ENS_GROUP_MASK(1879048192),
  ENS_GROUP_ERRNO(0),
  ENS_GROUP_ESPEAK_NG(268435456),
  ENS_COMPILE_ERROR(268435967),
  ENS_VERSION_MISMATCH(268436223),
  ENS_FIFO_BUFFER_FULL(268436479),
  ENS_NOT_INITIALIZED(268436735),
  ENS_AUDIO_ERROR(268436991),
  ENS_VOICE_NOT_FOUND(268437247),
  ENS_MBROLA_NOT_FOUND(268437503),
  ENS_MBROLA_VOICE_NOT_FOUND(268437759),
  ENS_EVENT_BUFFER_FULL(268438015),
  ENS_NOT_SUPPORTED(268438271),
  ENS_UNSUPPORTED_PHON_FORMAT(268438527),
  ENS_NO_SPECT_FRAMES(268438783),
  ENS_EMPTY_PHONEME_MANIFEST(268439039),
  ENS_SPEECH_STOPPED(268439295),
  ENS_UNKNOWN_PHONEME_FEATURE(268439551),
  ENS_UNKNOWN_TEXT_ENCODING(268439807);

  static const ENS_OK = ENS_GROUP_ERRNO;

  final int value;
  const espeak_ng_STATUS(this.value);

  static espeak_ng_STATUS fromValue(int value) => switch (value) {
        1879048192 => ENS_GROUP_MASK,
        0 => ENS_GROUP_ERRNO,
        268435456 => ENS_GROUP_ESPEAK_NG,
        268435967 => ENS_COMPILE_ERROR,
        268436223 => ENS_VERSION_MISMATCH,
        268436479 => ENS_FIFO_BUFFER_FULL,
        268436735 => ENS_NOT_INITIALIZED,
        268436991 => ENS_AUDIO_ERROR,
        268437247 => ENS_VOICE_NOT_FOUND,
        268437503 => ENS_MBROLA_NOT_FOUND,
        268437759 => ENS_MBROLA_VOICE_NOT_FOUND,
        268438015 => ENS_EVENT_BUFFER_FULL,
        268438271 => ENS_NOT_SUPPORTED,
        268438527 => ENS_UNSUPPORTED_PHON_FORMAT,
        268438783 => ENS_NO_SPECT_FRAMES,
        268439039 => ENS_EMPTY_PHONEME_MANIFEST,
        268439295 => ENS_SPEECH_STOPPED,
        268439551 => ENS_UNKNOWN_PHONEME_FEATURE,
        268439807 => ENS_UNKNOWN_TEXT_ENCODING,
        _ => throw ArgumentError('Unknown value for espeak_ng_STATUS: $value'),
      };

  @override
  String toString() {
    if (this == ENS_GROUP_ERRNO)
      return "espeak_ng_STATUS.ENS_GROUP_ERRNO, espeak_ng_STATUS.ENS_OK";
    return super.toString();
  }
}

enum espeak_ng_OUTPUT_MODE {
  ENOUTPUT_MODE_SYNCHRONOUS(1),
  ENOUTPUT_MODE_SPEAK_AUDIO(2);

  final int value;
  const espeak_ng_OUTPUT_MODE(this.value);

  static espeak_ng_OUTPUT_MODE fromValue(int value) => switch (value) {
        1 => ENOUTPUT_MODE_SYNCHRONOUS,
        2 => ENOUTPUT_MODE_SPEAK_AUDIO,
        _ => throw ArgumentError(
            'Unknown value for espeak_ng_OUTPUT_MODE: $value'),
      };
}

enum espeak_ng_VOICE_GENDER {
  ENGENDER_UNKNOWN(0),
  ENGENDER_MALE(1),
  ENGENDER_FEMALE(2),
  ENGENDER_NEUTRAL(3);

  final int value;
  const espeak_ng_VOICE_GENDER(this.value);

  static espeak_ng_VOICE_GENDER fromValue(int value) => switch (value) {
        0 => ENGENDER_UNKNOWN,
        1 => ENGENDER_MALE,
        2 => ENGENDER_FEMALE,
        3 => ENGENDER_NEUTRAL,
        _ => throw ArgumentError(
            'Unknown value for espeak_ng_VOICE_GENDER: $value'),
      };
}

final class espeak_ng_ERROR_CONTEXT_ extends ffi.Opaque {}

typedef espeak_ng_ERROR_CONTEXT = ffi.Pointer<espeak_ng_ERROR_CONTEXT_>;
