// espeak-ng config.h for Dart Native Assets build
//
// Normally generated by autotools/cmake. We provide a static version
// since we compile directly with CBuilder.

#define PACKAGE_VERSION "1.52-dev"

// Override PATH_ESPEAK_DATA — the original macro uses a comma expression
// that doesn't work as a string. We pass the data path at runtime anyway.
#define PATH_ESPEAK_DATA "/usr/share/espeak-ng-data"

#if defined(_WIN32) || defined(_WIN64)
#define _CRT_SECURE_NO_WARNINGS
#define _CRT_NONSTDC_NO_DEPRECATE
#endif

#if defined(__APPLE__)
#include <libkern/OSByteOrder.h>

#ifndef htole16
#define htole16(x) OSSwapHostToLittleInt16(x)
#endif
#ifndef le16toh
#define le16toh(x) OSSwapLittleToHostInt16(x)
#endif
#ifndef htole32
#define htole32(x) OSSwapHostToLittleInt32(x)
#endif
#ifndef le32toh
#define le32toh(x) OSSwapLittleToHostInt32(x)
#endif
#ifndef htole64
#define htole64(x) OSSwapHostToLittleInt64(x)
#endif
#ifndef le64toh
#define le64toh(x) OSSwapLittleToHostInt64(x)
#endif
#endif
