// espeak-ng config.h for Dart Native Assets build
//
// Normally generated by autotools/cmake. We provide a static version
// since we compile directly with CBuilder.

#define PACKAGE_VERSION "1.52-dev"

// Override PATH_ESPEAK_DATA — the original macro uses a comma expression
// that doesn't work as a string. We pass the data path at runtime anyway.
#define PATH_ESPEAK_DATA "/usr/share/espeak-ng-data"

#if defined(_WIN32) || defined(_WIN64)
#define _CRT_SECURE_NO_WARNINGS
#define _CRT_NONSTDC_NO_DEPRECATE
#endif
